# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/compact',
                'doc_host': 'https://thechandru.github.io',
                'git_url': 'https://github.com/thechandru/compact',
                'lib_path': 'compact'},
  'syms': {'compact.core': {'compact.core.foo': ('core.html#foo', 'compact/core.py')}}}
