"""Scheme R5RS implementation in Python

Docs: https://thechandru.github.io/compactcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['pair_primitives', 'pair2list', 'scm_apply', 'scm_eval_one_step', 'scm_eval_tco', 'Env', 'scm_sub', 'scm_div',
           'is_num', 'is_sym', 'is_list', 'is_pair', 'body_expr', 'arity', 'bind_params', 'qq']

# %% ../nbs/00_core.ipynb #a2531ffc
from fastcore.basics import store_attr, first

# %% ../nbs/00_core.ipynb #2660d14a
from .reader import *
from .types import *

# %% ../nbs/00_core.ipynb #5854068b
def pair2list(p):
    "walk a Pair chain into a python list"
    return list(p)

# %% ../nbs/00_core.ipynb #48103d34
def scm_apply(fn, args): return fn(*args)

# %% ../nbs/00_core.ipynb #fd519e55
def scm_eval_one_step(expr, env, sfs=()):
    "eval-uate lisp expressions given an environment and handlers for special forms"
    # Atoms
    if isinstance(expr, Symbol): return env[expr.s]
    if not isinstance(expr, Pair): return expr

    # lists
    hd, body = car(expr), pair2list(cdr(expr))

    if isinstance(hd, Symbol) and hd.s in sfs: return sfs[hd.s](body, env, sfs)
    fn = scm_eval_tco(hd, env, sfs)
    if isinstance(fn, Macro): return Thunk(fn.fn(*body), env)

    return scm_apply(fn, [scm_eval_tco(o, env, sfs) for o in body])

# %% ../nbs/00_core.ipynb #12289072
def scm_eval_tco(expr, env, sfs=()):
    "eval but with tail call optimization"
    while True:
        r = scm_eval_one_step(expr, env, sfs)
        if isinstance(r, Thunk): expr, env = r.expr, r.env
        else: return r

# %% ../nbs/00_core.ipynb #24df7be0
class Env:
    "this is an implementation of env for scheme eval()"
    def __init__(self, d, primitives:dict=(), parent=None): store_attr(cast=True)

    def __getitem__(self, k):
        s = self.find(k)
        if s is not None: 
            # there could be collisions for keys in primitives and globals()
            # for instance if `list` is called in scheme we want the builtin version
            # in python list will return what is in globals
            # (define list 42) is the moral equivalent of list = 42 - they will overwrite what's in globals
            if k in s.primitives: return s.primitives[k]
            return s.d[k]
        raise KeyError(k)

    def __setitem__(self, k, v): self.d[k] = v

    def __contains__(self, k): return self.find(k) is not None

    def update(self, d): self.primitives.update(d)

    def find(self, k):
        if k in self.d | self.primitives: return self
        if self.parent is not None: return self.parent.find(k)
        return None
    
    def new_frame(self, bindings=()):
        return Env(dict(bindings), parent=self)



# %% ../nbs/00_core.ipynb #92aed813
import math, operator as op

def scm_sub(x, *xs): return x - sum(xs) if xs else -x
def scm_div(x, *xs): return 1/x if not xs else x / math.prod(xs)

def is_num(x): return not isinstance(x, bool) and isinstance(x, (int, float, complex))
def is_sym(x): return isinstance(x, Symbol)

_builtin = {
    "+": lambda *xs: sum(xs),
    "*": lambda *xs: math.prod(xs), 
    "/": scm_div,
    "-": scm_sub,
    ">": op.gt, 
    "<": op.lt, 
    "=": lambda x,y: is_num(x) and is_num(y) and x == y,
    "<=": op.le,
    ">=": op.ge,
    
    "number?": is_num,
    "string?": lambda x: isinstance(x, str),
    "symbol?": is_sym,
    "boolean?": lambda x: isinstance(x, bool),
}

def is_list(x): return x is Nil or (isinstance(x, Pair) and is_list(cdr(x)))
def is_pair(x): return isinstance(x, Pair)

pair_primitives = {
    "list": lambda *xs: list2pair(list(xs)),
    "cons": cons, 
    "car": car, 
    "cdr": cdr, 
    "null?": lambda x: x is Nil, 
    "pair?": is_pair,
    "list?": is_list,
    }

# %% ../nbs/00_core.ipynb #cf72bbe6
def _sf_quote(xs, env, sfs): return xs[0]

# %% ../nbs/00_core.ipynb #f72f6bd8
def _sf_if_tco(xs, env, sfs):
    cond,then_,else_ = xs
    br = else_ if scm_eval_tco(cond, env, sfs) is False else then_
    return Thunk(br, env)


# %% ../nbs/00_core.ipynb #a1c91964
def body_expr(body): return body[0] if len(body) == 1 else cons(Symbol("begin"), list2pair(body))

# %% ../nbs/00_core.ipynb #efce91e6
def arity(ps, vs):
    ps = list(ps)
    if len(vs) == len(ps): return vs
    raise ValueError(f"incorrect number of vs passed (wanted: {len(ps)}, got: {len(vs)})")

# %% ../nbs/00_core.ipynb #e357365b
def bind_params(ps, vs):
    if isinstance(ps, Symbol): return {ps.s: list(vs)}
    return dict(zip([p.s for p in ps], arity(ps, vs)))

# %% ../nbs/00_core.ipynb #cf48dc77
def _sf_define_tco(xs, env, sfs):
    def _mkfn(sym, expr): 
        if not isinstance(sym, Symbol): raise SyntaxError(f"{sym} must be a symbol")
        env[sym.s] = scm_eval_tco(expr, env, sfs)
        return sym.s

    arg0, *rest = xs
    if isinstance(arg0, Symbol): return _mkfn(arg0, body_expr(rest))
    if isinstance(arg0, Pair): return _mkfn(car(arg0), cons(Symbol("lambda"), cons(cdr(arg0), list2pair(rest))))

# %% ../nbs/00_core.ipynb #d872eca0
def _sf_lambda_tco(xs, env, sfs): 
    params, *body = xs
    def procedure(*args):
        return Thunk(body_expr(body), env.new_frame(bind_params(params, args)))
    return procedure
    # return lambda *args: Thunk(body_expr(body), Env(**bind_params(params, args), parent=env))

# %% ../nbs/00_core.ipynb #578f1427
def _sf_begin_tco(xs, env, sfs):
    for o in xs[:-1]: scm_eval_tco(o, env, sfs)
    return Thunk(xs[-1], env)

# %% ../nbs/00_core.ipynb #7300b953
def _macro(args, env, sfs):
    params, *body = args
    return Macro(lambda *vals: scm_eval_tco(body_expr(body), env.new_frame(bind_params(params, vals)), sfs))

# %% ../nbs/00_core.ipynb #f3037817
def qq(x, env, sfs, depth=1):
    "handle ` , and ,@"
    QQ, UQ, UQS = Symbol("quasiquote"), Symbol("unquote"), Symbol("unquote-splicing")
    def tagged(o, sym): return isinstance(o, Pair) and o.car == sym and isinstance(o.cdr, Pair) and o.cdr.cdr is Nil

    if not isinstance(x, Pair): return x
    if tagged(x, QQ): return cons(QQ, cons(qq(car(cdr(x)), env, sfs, depth+1), Nil))
    if tagged(x, UQ):
        y = car(cdr(x))
        return scm_eval_tco(y, env, sfs) if depth == 1 else cons(UQ, cons(qq(y, env, sfs, depth-1), Nil))
    if tagged(x, UQS):
        if depth == 1: raise SyntaxError("unquote-splicing only valid inside a list")
        return cons(UQS, cons(qq(car(cdr(x)), env, sfs, depth-1), Nil))

    def walk(p):
        if not isinstance(p, Pair): return p
        o, rest = p.car, p.cdr
        if tagged(o, UQS) and depth == 1: return list2pair(pair2list(scm_eval_tco(car(cdr(o)), env, sfs)), walk(rest))
        return cons(qq(o, env, sfs, depth), walk(rest))
    return walk(x)

# %% ../nbs/00_core.ipynb #78732c31
def _sf_quasiquote(args, env, sfs): return qq(args[0], env, sfs)
