"""Scheme implementation in Python

Docs: https://thechandru.github.io/compact/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['lisp', 'Env', 'scm_apply', 'scm_eval_one_step', 'scm_eval_tco', 'scm_sub', 'scm_div', 'is_num', 'is_sym', 'is_list',
           'is_pair', 'body_expr', 'arity', 'bind_params', 'qq', 'LispCtx']

# %% ../nbs/00_core.ipynb #e086d109
import math, operator as op

# %% ../nbs/00_core.ipynb #a2531ffc
from fastcore.basics import store_attr, first

# %% ../nbs/00_core.ipynb #2660d14a
from .reader import *
from .types import *

# %% ../nbs/00_core.ipynb #4b978579
class Env:
    "implementation of env for scheme eval()."
    def __init__(self, d, primitives:dict=(), parent=None): store_attr(cast=True)

    def __getitem__(self, k):
        s = self.find(k)
        if s is not None: 
            # there could be collisions for keys in primitives and globals()
            # for instance if `list` is called in scheme we want the builtin version
            # in python list will return what is in globals
            # (define list 42) is the moral equivalent of list = 42 - they will overwrite what's in globals
            if k in s.primitives: return s.primitives[k]
            return s.d[k]
        raise KeyError(k)

    def __setitem__(self, k, v): self.d[k] = v

    def __contains__(self, k): return self.find(k) is not None

    def update(self, d): self.primitives.update(d)

    def find(self, k):
        if k in self.d | self.primitives: return self
        if self.parent is not None: return self.parent.find(k)
        return None
    
    def is_primitive(self, k):
        if self.parent is None: return k in self.primitives
        return self.parent.is_primitive(k)

    def new_frame(self, bindings=()):
        return Env(dict(bindings), parent=self)


# %% ../nbs/00_core.ipynb #48103d34
def scm_apply(fn, args): return fn(*args)

# %% ../nbs/00_core.ipynb #fd519e55
def scm_eval_one_step(expr, env, sfs=()):
    "eval-uate lisp expressions given an environment and handlers for special forms"
    # Atoms
    if isinstance(expr, Symbol): return env[expr.s]
    if not isinstance(expr, list): return expr

    # lists
    hd, body = expr[0], expr[1:]

    if isinstance(hd, Symbol) and hd.s in sfs: return sfs[hd.s](body, env, sfs)
    fn = scm_eval_tco(hd, env, sfs)
    if isinstance(fn, Macro): return Thunk(fn.fn(*body), env)

    return scm_apply(fn, [scm_eval_tco(o, env, sfs) for o in body])

# %% ../nbs/00_core.ipynb #12289072
def scm_eval_tco(expr, env, sfs=()):
    "eval but with tail call optimization"
    while True:
        r = scm_eval_one_step(expr, env, sfs)
        if isinstance(r, Thunk): expr, env = r.expr, r.env
        else: return r

# %% ../nbs/00_core.ipynb #f0091913
def scm_sub(x, *xs): return x - sum(xs) if xs else -x
def scm_div(x, *xs): return 1/x if not xs else x / math.prod(xs)

def is_num(x): return not isinstance(x, bool) and isinstance(x, (int, float, complex))
def is_sym(x): return isinstance(x, Symbol)

_builtin = {
    "+": lambda *xs: sum(xs),
    "*": lambda *xs: math.prod(xs), 
    "/": scm_div,
    "-": scm_sub,
    ">": op.gt, 
    "<": op.lt, 
    "=": lambda x,y: is_num(x) and is_num(y) and x == y,
    "<=": op.le,
    ">=": op.ge,
    
    "number?": is_num,
    "string?": lambda x: isinstance(x, str),
    "symbol?": is_sym,
    "boolean?": lambda x: isinstance(x, bool),
}

def is_list(x): return isinstance(x, list)
def is_pair(x): return isinstance(x, list) and bool(x)

_builtin |= {
    "list": lambda *xs: list(xs),
    "cons": lambda x,y: [x] + y,
    "car": lambda x: x[0],
    "cdr": lambda x: x[1:],
    "null?": lambda x: x == [],
    "pair?": is_pair,
    "list?": is_list,
}

# %% ../nbs/00_core.ipynb #cf72bbe6
def _sf_quote(xs, env, sfs): return xs[0]

# %% ../nbs/00_core.ipynb #33b4f9f4
def _sf_begin_tco(xs, env, sfs):
    for o in xs[:-1]: scm_eval_tco(o, env, sfs)
    return Thunk(xs[-1], env)

# %% ../nbs/00_core.ipynb #3442b420
def body_expr(body): return body[0] if len(body) == 1 else [Symbol("begin")] + body

# %% ../nbs/00_core.ipynb #f72f6bd8
def _sf_if_tco(xs, env, sfs):
    cond,then_,else_ = xs
    br = else_ if scm_eval_tco(cond, env, sfs) is False else then_
    return Thunk(br, env)


# %% ../nbs/00_core.ipynb #9a549a5a
def _sf_lambda_tco(xs, env, sfs): 
    params, *body = xs
    def procedure(*args):
        return Thunk(body_expr(body), env.new_frame(bind_params(params, args)))
    return procedure
    # return lambda *args: Thunk(body_expr(body), Env(**bind_params(params, args), parent=env))

# %% ../nbs/00_core.ipynb #efce91e6
def arity(ps, vs):
    if len(vs) == len(ps): return vs
    raise ValueError(f"incorrect number of vs passed (wanted: {len(ps)}, got: {len(vs)})")

def bind_params(ps, vs):
    if isinstance(ps, Symbol): return {ps.s: list(vs)}
    return dict(zip([p.s for p in ps], arity(ps, vs)))

# %% ../nbs/00_core.ipynb #cf48dc77
def _sf_define_tco(xs, env, sfs):
    def _mkfn(sym, expr): 
        if not isinstance(sym, Symbol): raise SyntaxError(f"{sym} must be a symbol")
        if env.is_primitive(sym.s): raise SyntaxError(f"cannot redefine primitive '{sym.s}'")
        env[sym.s] = scm_eval_tco(expr, env, sfs)
        return sym.s

    arg0, *rest = xs
    if isinstance(arg0, Symbol): return _mkfn(arg0, body_expr(rest))
    if isinstance(arg0, list): return _mkfn(arg0[0], [Symbol("lambda"), arg0[1:]] + rest)

# %% ../nbs/00_core.ipynb #d3431242
def _sf_set(xs, env, sfs):
    sym, expr = xs
    if not isinstance(sym, Symbol): raise SyntaxError(f"set! argument {sym} must be a symbol")
    e = env.find(sym.s)
    if e is None: raise NameError(sym.s)

    e[sym.s] = scm_eval_tco(expr, env, sfs)
    return sym.s

# %% ../nbs/00_core.ipynb #8746edea
def _sf_let(xs, env, sfs):
    binds, *body = xs
    new_env = env.new_frame({name.s: scm_eval_tco(val, env, sfs) for name, val in binds})

    return Thunk(body_expr(body), new_env)

# %% ../nbs/00_core.ipynb #7300b953
def _macro(args, env, sfs):
    params, *body = args
    return Macro(lambda *vals: scm_eval_tco(body_expr(body), env.new_frame(bind_params(params, vals)), sfs))

# %% ../nbs/00_core.ipynb #f3037817
def qq(x, env, sfs, depth=1):
    "handle ` , and ,@"
    QQ, UQ, UQS = Symbol("quasiquote"), Symbol("unquote"), Symbol("unquote-splicing")
    def tagged(o, sym): return isinstance(o, list) and len(o) == 2 and o[0] == sym

    if not isinstance(x, list): return x
    if tagged(x, QQ): return [QQ, qq(x[1], env, sfs, depth+1)]
    if tagged(x, UQ):
        return scm_eval_tco(x[1], env, sfs) if depth == 1 else [UQ, qq(x[1], env, sfs, depth-1)]
    if tagged(x, UQS):
        if depth == 1: raise SyntaxError("unquote-splicing only valid inside a list")
        return [UQS, qq(x[1], env, sfs, depth-1)]

    def walk(lst):
        result = []
        for o in lst:
            if tagged(o, UQS) and depth == 1: result.extend(scm_eval_tco(o[1], env, sfs))
            else: result.append(qq(o, env, sfs, depth))
        return result
    return walk(x)

# %% ../nbs/00_core.ipynb #78732c31
def _sf_quasiquote(args, env, sfs): return qq(args[0], env, sfs)

# %% ../nbs/00_core.ipynb #1d3be5c7
_all_sfs = {
    "begin": _sf_begin_tco,
    "if": _sf_if_tco,
    "define": _sf_define_tco,
    "lambda": _sf_lambda_tco,
    "macro": _macro,
    "set!": _sf_set,
    "let": _sf_let,
    "quote": _sf_quote,
    "quasiquote": _sf_quasiquote,
    
}

# %% ../nbs/00_core.ipynb #3ddb8440
class LispCtx:
    def __init__(self):
        self.env = Env(globals(), primitives=_builtin)
    
    def __rmatmul__(self, s):
        return scm_eval_tco(parse(s), self.env, _all_sfs)
        
lisp = LispCtx()
