"""Scheme implementation in Python

Docs: https://thechandru.github.io/compact/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['lisp', 'Env', 'scm_apply', 'Procedure', 'scm_eval_one_step', 'scm_eval_tco', 'LispCtx']

# %% ../nbs/00_core.ipynb #dd1b83e1
import math, operator as op
import inspect
from fastcore.basics import store_attr, first, last

from .reader import *
from .types import *

# %% ../nbs/00_core.ipynb #4b978579
class Env:
    "implementation of env for scheme eval()."
    def __init__(self, d, primitives:dict=(), parent=None): store_attr(cast=True)

    def __getitem__(self, k):
        s = self.find(k)
        if s is not None: 
            # we currently do not allow shadowing of primitives - this is not ideal
            if k in s.primitives: return s.primitives[k]
            return s.d[k]
        raise KeyError(k)

    def __setitem__(self, k, v): self.d[k] = v

    def __contains__(self, k): return self.find(k) is not None

    def update(self, d): self.primitives.update(d)

    def find(self, k):
        if k in self.d | self.primitives: return self
        if self.parent is not None: return self.parent.find(k)
        return None
    
    def is_primitive(self, k):
        if self.parent is None: return k in self.primitives
        return self.parent.is_primitive(k)

    def new_frame(self, bindings=()):
        return Env(dict(bindings), parent=self)

# %% ../nbs/00_core.ipynb #48103d34
def scm_apply(fn, args):
    if isinstance(fn, Procedure): return fn._thunk(*args)
    return fn(*args)

# %% ../nbs/00_core.ipynb #52f0b557
class Procedure:
    "a dual use wrapper for scm_eval as well as python callers"
    def __init__(self, params, body, env, sfs): store_attr()
    def _thunk(self, *args): 
        "return a Thunk so this can be executed inside the eval loop"
        return Thunk(_body_expr(self.body), self.env.new_frame(_bind_params(self.params, args)))
    def __call__(self, *args): 
        "if called directly from python, eval it for the caller"
        return scm_eval_tco(_body_expr(self.body), 
            self.env.new_frame(_bind_params(self.params, args)), self.sfs)

# %% ../nbs/00_core.ipynb #fd519e55
def scm_eval_one_step(expr, env, sfs=()):
    "eval-uate lisp expressions given an environment and handlers for special forms"
    # Atoms
    if isinstance(expr, Symbol): return env[expr.s]
    if not isinstance(expr, list): return expr

    # lists
    hd, body = expr[0], expr[1:]

    if isinstance(hd, Symbol) and hd.s in sfs: return sfs[hd.s](body, env, sfs)
    fn = scm_eval_tco(hd, env, sfs)
    if isinstance(fn, Macro): return Thunk(fn.fn(*body), env)

    return scm_apply(fn, [scm_eval_tco(o, env, sfs) for o in body])

# %% ../nbs/00_core.ipynb #12289072
def scm_eval_tco(expr, env, sfs=()):
    "eval but with tail call optimization"
    while True:
        r = scm_eval_one_step(expr, env, sfs)
        if isinstance(r, Thunk): expr, env = r.expr, r.env
        else: return r

# %% ../nbs/00_core.ipynb #ae30bc6b
def _scm_error(msg, *irritants): raise Exception(msg if not irritants else f"{msg} {' '.join(map(repr, irritants))}")
def _scm_sub(x, *xs): return x - sum(xs) if xs else -x
def _scm_div(x, *xs): return 1/x if not xs else x / math.prod(xs)
def _is_num(x): return not isinstance(x, bool) and isinstance(x, (int, float, complex))
def _is_sym(x): return isinstance(x, Symbol)
def _is_sym_eq(x, s): return _is_sym(x) and x.s == s
def _is_list(x): return isinstance(x, list)
def _is_pair(x): return isinstance(x, list) and bool(x)
def _scm_equal(x, y):
    if type(x) != type(y): return False
    if isinstance(x, list): return len(x) == len(y) and all(_scm_equal(a,b) for a,b in zip(x,y))
    return x == y
def _str2num(s):
    try: return int(s)
    except ValueError:
        try: return float(s)
        except ValueError: return False

_builtin = {
    "+": lambda *xs: sum(xs), 
    "*": lambda *xs: math.prod(xs),
    "-": _scm_sub, "/": _scm_div,
    "=": lambda x,y: _is_num(x) and _is_num(y) and x == y,
    "<": op.lt, ">": op.gt, "<=": op.le, ">=": op.ge,
}
_builtin |= {
    "number?": _is_num, "string?": lambda x: isinstance(x, str),
    "symbol?": _is_sym, "boolean?": lambda x: isinstance(x, bool),
    "null?": lambda x: x == [], "pair?": _is_pair, "list?": _is_list,
}
_builtin |= {
    "list": lambda *xs: list(xs), "cons": lambda x,y: [x] + y,
    "car": lambda x: x[0], "cdr": lambda x: x[1:],
}
_builtin |= {
    "string-append": lambda *xs: "".join(xs),
    "string-length": len,
    "substring": lambda s,i,j: s[i:j],
    "number->string": str, "string->number": _str2num,
}
_builtin |= {
    "floor": math.floor, "ceiling": math.ceil,
    "round": round, "truncate": math.trunc,
    "abs": abs, "min": min, "max": max,
    "sqrt": math.sqrt, "expt": pow, "modulo": op.mod,
    "remainder": lambda x,y: x - int(x/y)*y,
}
_builtin |= {"symbol->string": lambda x: x.s, "string->symbol": Symbol,
    "equal?": _scm_equal,
    "not": lambda x: x is False, "error": _scm_error}

# %% ../nbs/00_core.ipynb #60d1560a
class LispCtx:
    "convenience lisp context for interop"
    def __init__(self):
        self.env = Env(globals(), primitives=_builtin)
        self.sfs = {}

    def sf(self, nm=None):
        def reg(fn):
            key = nm or fn.__name__.removeprefix('_sf_').replace('_', '-')
            self.sfs[key] = fn; return fn
        return reg

    def __rmatmul__(self, s):
        caller_globals = inspect.stack()[1][0].f_globals
        env = Env(caller_globals, primitives=self.env.primitives, parent=self.env)
        exprs = parse_all(s)
        expr = exprs[0] if len(exprs) == 1 else [Symbol("begin")] + exprs
        return scm_eval_tco(expr, env, self.sfs)

    def register_magic(self):        
        from IPython.core.magic import register_cell_magic
        register_cell_magic('lisp')(lambda line, cell: cell @ self)

lisp = LispCtx()

# %% ../nbs/00_core.ipynb #cf72bbe6
@lisp.sf()
def _sf_quote(xs, env, sfs): return xs[0]

# %% ../nbs/00_core.ipynb #33b4f9f4
@lisp.sf()
def _sf_begin(xs, env, sfs):
    for o in xs[:-1]: scm_eval_tco(o, env, sfs)
    return Thunk(xs[-1], env)

# %% ../nbs/00_core.ipynb #3442b420
def _body_expr(body): return body[0] if len(body) == 1 else [Symbol("begin")] + body

def _bind_params(ps, vs):
    match ps:
        case Symbol(s=nm): return {nm: list(vs)}
        case [*fixed, Symbol(s="."), Symbol(s=rest)]:
            return dict(zip([p.s for p in fixed], vs)) | {rest: list(vs[len(fixed):])}
        case _:
            if len(vs) != len(ps): raise ValueError(f"arity mismatch: wanted {len(ps)}, got {len(vs)}")
            return dict(zip([p.s for p in ps], vs))

# %% ../nbs/00_core.ipynb #1582e36f
@lisp.sf()
def _sf_if(xs, env, sfs):
    cond,then_,else_ = xs
    br = else_ if scm_eval_tco(cond, env, sfs) is False else then_
    return Thunk(br, env)

# %% ../nbs/00_core.ipynb #9a549a5a
@lisp.sf()
def _sf_lambda(xs, env, sfs): return Procedure(xs[0], xs[1:], env, sfs)

# %% ../nbs/00_core.ipynb #cf48dc77
@lisp.sf()
def _sf_define(xs, env, sfs):
    def _mkfn(sym, expr):
        if not isinstance(sym, Symbol): raise SyntaxError(f"{sym} must be a symbol")
        if env.is_primitive(sym.s): raise SyntaxError(f"cannot redefine primitive '{sym.s}'")
        env[sym.s] = scm_eval_tco(expr, env, sfs)
        return sym.s
    arg0, *rest = xs
    if isinstance(arg0, Symbol): return _mkfn(arg0, _body_expr(rest))
    if isinstance(arg0, list): return _mkfn(arg0[0], [Symbol("lambda"), arg0[1:]] + rest)

# %% ../nbs/00_core.ipynb #d3431242
@lisp.sf("set!")
def _sf_set(xs, env, sfs):
    sym, expr = xs
    if not isinstance(sym, Symbol): raise SyntaxError(f"set! argument {sym} must be a symbol")
    e = env.find(sym.s)
    if e is None: raise NameError(sym.s)

    e[sym.s] = scm_eval_tco(expr, env, sfs)
    return sym.s

# %% ../nbs/00_core.ipynb #8746edea
@lisp.sf()
def _sf_let(xs, env, sfs):
    ev = lambda x: scm_eval_tco(x, env, sfs)
    match xs:
        case [Symbol(s=nm), binds, *body]:  # (let loop ((i 0)) body)
            pairs = [(o[0], ev(o[1])) for o in binds]
            params, inits = zip(*pairs) if pairs else ([], [])
            new_env = env.new_frame({nm: None})
            new_env[nm] = _sf_lambda([list(params)] + body, new_env, sfs)
            return new_env[nm](*inits)
        case [binds, *body]:                # (let ((x 1)) body)
            new_env = env.new_frame({n.s: ev(v) for n,v in binds})
            return Thunk(_body_expr(body), new_env)

# %% ../nbs/00_core.ipynb #e81c3961
@lisp.sf()
def _sf_cond(xs, env, sfs):
    for test, *body in xs:
        if _is_sym_eq(test, 'else') or scm_eval_tco(test, env, sfs) is not False:
            return Thunk(_body_expr(body), env)

# %% ../nbs/00_core.ipynb #ca481cda
@lisp.sf()
def _sf_and(xs, env, sfs):
    if not xs: return True
    for o in xs[:-1]:
        if scm_eval_tco(o, env, sfs) is False: return False
    return Thunk(xs[-1], env)

@lisp.sf()
def _sf_or(xs, env, sfs):
    if not xs: return False
    for o in xs[:-1]:
        v = scm_eval_tco(o, env, sfs)
        if v is not False: return v
    return Thunk(xs[-1], env)

# %% ../nbs/00_core.ipynb #9070b61c
@lisp.sf("let*")
def _sf_let_star(xs, env, sfs):
    binds, *body = xs
    for name, val in binds:
        env = env.new_frame({name.s: scm_eval_tco(val, env, sfs)})
    return Thunk(_body_expr(body), env)

# %% ../nbs/00_core.ipynb #0167198f
@lisp.sf()
def _sf_letrec(xs, env, sfs):
    binds, *body = xs
    new_env = env.new_frame({name.s: None for name, _ in binds})
    for name, val in binds: new_env[name.s] = scm_eval_tco(val, new_env, sfs)
    return Thunk(_body_expr(body), new_env)

# %% ../nbs/00_core.ipynb #935f80b2
@lisp.sf()
def _sf_fold_left(xs, env, sfs):
    fn, acc, lst = [scm_eval_tco(x, env, sfs) for x in xs]
    for x in lst: acc = _invoke(fn, [acc, x], sfs)
    return acc

@lisp.sf()
def _sf_fold_right(xs, env, sfs):
    fn, init, lst = [scm_eval_tco(x, env, sfs) for x in xs]
    acc = init
    for x in reversed(lst): acc = _invoke(fn, [x, acc], sfs)
    return acc

# %% ../nbs/00_core.ipynb #d823425c
@lisp.sf()
def _sf_case(xs, env, sfs):
    key = scm_eval_tco(xs[0], env, sfs)
    for vals, *body in xs[1:]:
        if _is_sym_eq(vals, 'else') or key in vals: return Thunk(_body_expr(body), env)

# %% ../nbs/00_core.ipynb #6115ce5e
def _invoke(fn, args, sfs):
    "call fn resolving any TCO thunk"
    r = scm_apply(fn, args)
    return scm_eval_tco(r.expr, r.env, sfs) if isinstance(r, Thunk) else r

# %% ../nbs/00_core.ipynb #eecbdd8b
@lisp.sf()
def _sf_apply(xs, env, sfs):
    fn   = scm_eval_tco(xs[0], env, sfs)
    args = [scm_eval_tco(o, env, sfs) for o in xs[1:-1]]
    last = scm_eval_tco(xs[-1], env, sfs)
    return _invoke(fn, args + list(last), sfs)

# %% ../nbs/00_core.ipynb #e2a3744a
@lisp.sf()
def _sf_map(xs, env, sfs):
    fn   = scm_eval_tco(xs[0], env, sfs)
    lsts = [scm_eval_tco(l, env, sfs) for l in xs[1:]]
    return [_invoke(fn, list(args), sfs) for args in zip(*lsts)]

# %% ../nbs/00_core.ipynb #810ac31e
@lisp.sf()
def _sf_filter(xs, env, sfs):
    fn  = scm_eval_tco(xs[0], env, sfs)
    lst = scm_eval_tco(xs[1], env, sfs)
    return [x for x in lst if _invoke(fn, [x], sfs) is not False]

# %% ../nbs/00_core.ipynb #a3316139
@lisp.sf()
def _sf_for_each(xs, env, sfs):
    fn   = scm_eval_tco(xs[0], env, sfs)
    lsts = [scm_eval_tco(l, env, sfs) for l in xs[1:]]
    for args in zip(*lsts): _invoke(fn, list(args), sfs)

# %% ../nbs/00_core.ipynb #7300b953
@lisp.sf("macro")
def _macro(args, env, sfs):
    params, *body = args
    return Macro(lambda *vals: scm_eval_tco(_body_expr(body), env.new_frame(_bind_params(params, vals)), sfs))

# %% ../nbs/00_core.ipynb #f3037817
def _qq(x, env, sfs, depth=1):
    "handle ` , and ,@"
    QQ, UQ, UQS = Symbol("quasiquote"), Symbol("unquote"), Symbol("unquote-splicing")
    def tagged(o, sym): return isinstance(o, list) and len(o) == 2 and o[0] == sym

    if not isinstance(x, list): return x
    if tagged(x, QQ): return [QQ, _qq(x[1], env, sfs, depth+1)]
    if tagged(x, UQ):
        return scm_eval_tco(x[1], env, sfs) if depth == 1 else [UQ, _qq(x[1], env, sfs, depth-1)]
    if tagged(x, UQS):
        if depth == 1: raise SyntaxError("unquote-splicing only valid inside a list")
        return [UQS, _qq(x[1], env, sfs, depth-1)]

    def walk(lst):
        result = []
        for o in lst:
            if tagged(o, UQS) and depth == 1: result.extend(scm_eval_tco(o[1], env, sfs))
            else: result.append(_qq(o, env, sfs, depth))
        return result
    return walk(x)

# %% ../nbs/00_core.ipynb #a689ab1e
"""
(define when (macro (cond . body) `(if ,cond (begin ,@body) #f)))
(define unless (macro (cond . body) `(if ,cond #f (begin ,@body))))
""" @ lisp

# %% ../nbs/00_core.ipynb #78732c31
@lisp.sf()
def _sf_quasiquote(args, env, sfs): return _qq(args[0], env, sfs)
