"""parsing lisp text into an AST

Docs: https://thechandru.github.io/compactreader.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_reader.ipynb.

# %% auto #0
__all__ = ['STR', 'COMMENT', 'DOT', 'ATOM', 'UNQ_SPL', 'PAREN', 'QUOTE', 'TOKEN_RE', 'Atom', 'lexer', 'parse_list', 'parser',
           'parse', 'parse_all']

# %% ../nbs/02_reader.ipynb #6d9127ac
import ast, re
from fastcore.basics import basic_repr, store_attr, first, last
from .types import *

# %% ../nbs/02_reader.ipynb #0add99dc
def Atom(s):
    "parse atoms, default this is a symbol"
    if s == "#t": return True
    if s == "#f": return False
    try: return ast.literal_eval(s)
    except Exception: return Symbol(s)


# %% ../nbs/02_reader.ipynb #f0e856db
STR = r'"(?:\\.|[^"\\])*"'  # string with spaces etc.
COMMENT = r';[^\n]*'

DOT = r'\.'

ATOM = r'''[^\s()`',;]+'''

UNQ_SPL = ',@'              # unquote splice
PAREN = '[()]'
QUOTE = "[`',]"

# order matters `,@` needs to show up before the single character `,`
TOKEN_RE = "|".join([STR, COMMENT, DOT, UNQ_SPL, PAREN, QUOTE, ATOM])

def lexer(s): return [t for t in re.findall(TOKEN_RE, s) if not t.startswith(';')]

# %% ../nbs/02_reader.ipynb #9bdf87dc
def parse_list(sl):
    if Symbol(s=".") in sl: raise SyntaxError("malformed dotted list")
    return sl

# %% ../nbs/02_reader.ipynb #ac1c8aca
def parser(toks):
    if not toks: raise SyntaxError("malformed list: unexpected EOF")
    

    t = toks.pop(0)
    if t == ')': raise SyntaxError("malformed list: unexpected )")
    if t == '(':
        sl = []
        while toks and toks[0] != ')': sl.append(parser(toks))
        if not toks: raise SyntaxError("malformed list: missing )")
        toks.pop(0)
        return parse_list(sl)
    sugar = {
        "'": "quote",
        "`": "quasiquote",
        ",": "unquote",
        ",@": "unquote-splicing",
    }
    if t in sugar: return [Symbol(sugar[t]), parser(toks)]

    return Atom(t)

# %% ../nbs/02_reader.ipynb #1838946d
def parse(s): 
    toks = lexer(s)
    r = parser(toks)
    if not toks: return r
    raise SyntaxError("unexpected tokens after expression")

# %% ../nbs/02_reader.ipynb #9ac3e7d4
def parse_all(s):
    toks = lexer(s)
    exprs = []
    while toks: exprs.append(parser(toks))
    return exprs
