"""Scheme types

Docs: https://thechandru.github.io/compacttypes.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_types.ipynb.

# %% auto #0
__all__ = ['Nil', 'cons', 'car', 'cdr', 'Symbol', 'Macro', 'Thunk', 'Pair', 'NilType', 'list2pair', 'pair_str']

# %% ../nbs/01_types.ipynb #56125ba3
from fastcore.basics import store_attr, basic_repr


# %% ../nbs/01_types.ipynb #bcd6a16c
class Symbol:
    "symbol is a `name` in Lisp"
    def __init__(self, s): store_attr()
    def __str__(self): return f"{self.s}"

    def __eq__(self, other): return isinstance(other, Symbol) and self.s == other.s
    def __hash__(self): return hash(self.s)
    
    __repr__ = basic_repr()

# %% ../nbs/01_types.ipynb #2a368749
class Macro:
    "holder of the function for late evaluation"
    def __init__(self, fn): store_attr()

# %% ../nbs/01_types.ipynb #66d47471
class Thunk:
    "a piece of computation that can be executed later"
    def __init__(self, expr, env): store_attr()

# %% ../nbs/01_types.ipynb #1ff6ea43
from fastcore.basics import patch, basic_repr

# %% ../nbs/01_types.ipynb #a142753a
class Pair:
    "a cons cell"
    __slots__ = ("car", "cdr")
    def __init__(self, car, cdr): self.car,self.cdr = car,cdr
    def __eq__(self, other): return isinstance(other, Pair) and self.car == other.car and self.cdr == other.cdr
    __repr__ = basic_repr("car,cdr")

# %% ../nbs/01_types.ipynb #f8c1dae5
class NilType:
    def __str__(self): return "()"
    def __repr__(self): return str(self)

# %% ../nbs/01_types.ipynb #39aafcad
Nil = NilType()

# %% ../nbs/01_types.ipynb #b6511cab
cons = lambda x,y: Pair(x, y)
car = lambda x: x.car
cdr = lambda x: x.cdr

# %% ../nbs/01_types.ipynb #08267157
def list2pair(lst, tail=Nil):
    "convert a python list into Scheme list / pair chain, ending in optional tail"
    if not isinstance(lst, list): return lst
    return tail if not lst else Pair(list2pair(lst[0]), list2pair(lst[1:], tail))

# %% ../nbs/01_types.ipynb #956d56cd
def pair_str(p):
    "string representation of a pair"
    if cdr(p) is Nil: return str(car(p))
    if isinstance(cdr(p), Pair): return f"{car(p)} {pair_str(cdr(p))}"

    return f"{car(p)} . {cdr(p)}"    

# %% ../nbs/01_types.ipynb #cbb32783
@patch
def __str__(self:Pair): return f"({pair_str(self)})"
