"""Scheme types

Docs: https://thechandru.github.io/compacttypes.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_types.ipynb.

# %% auto #0
__all__ = ['Nil', 'cons', 'car', 'cdr', 'pair_primitives', 'Pair', 'NilType', 'list2pair', 'pair_str', 'is_list', 'is_pair']

# %% ../nbs/01_types.ipynb #1ff6ea43
from fastcore.basics import patch, basic_repr

# %% ../nbs/01_types.ipynb #0081689e
class Pair:
    "a cons cell"
    __slots__ = ("car", "cdr")
    def __init__(self, car, cdr): self.car,self.cdr = car,cdr
    def __eq__(self, other): return isinstance(other, Pair) and self.car == other.car and self.cdr == other.cdr
    __repr__ = basic_repr("car,cdr")

class NilType:
    def __str__(self): return "()"
    def __repr__(self): return str(self)

Nil = NilType()

# %% ../nbs/01_types.ipynb #b6511cab
cons = lambda x,y: Pair(x, y)
car = lambda x: x.car
cdr = lambda x: x.cdr

# %% ../nbs/01_types.ipynb #08267157
def list2pair(lst, tail=Nil):
    "convert a python list into Scheme list / pair chain, ending in optional tail"
    if not isinstance(lst, list): return lst
    return tail if not lst else Pair(list2pair(lst[0]), list2pair(lst[1:], tail))

# %% ../nbs/01_types.ipynb #956d56cd
def pair_str(p):
    "string representation of a pair"
    if cdr(p) is Nil: return str(car(p))
    if isinstance(cdr(p), Pair): return f"{car(p)} {pair_str(cdr(p))}"

    return f"{car(p)} . {cdr(p)}"    

# %% ../nbs/01_types.ipynb #cbb32783
@patch
def __str__(self:Pair): return f"({pair_str(self)})"

# %% ../nbs/01_types.ipynb #d43fb4b8
def is_list(x): return x is Nil or (isinstance(x, Pair) and is_list(cdr(x)))
def is_pair(x): return isinstance(x, Pair)

pair_primitives = {
    "list": lambda *xs: list2pair(list(xs)),
    "cons": cons, 
    "car": car, 
    "cdr": cdr, 
    "null?": lambda x: x is Nil, 
    "pair?": is_pair,
    "list?": is_list,
    }
