[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "compact"
dynamic = ["version"]
description = "Tiny implementation of scheme in Python"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Solveit", email = "nobody@fast.ai"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []

[project.urls]
Repository = "https://github.com/thechandru/compact"
Documentation = "https://thechandru.github.io/compact/"

[project.entry-points.nbdev]
compact = "compact._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "compact.__version__"}

[tool.setuptools.packages.find]
include = ["compact"]

[tool.nbdev]
