"""Scheme types

Docs: https://thechandru.github.io/compact/types.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_types.ipynb.

# %% auto #0
__all__ = ['Symbol', 'Macro', 'Thunk']

# %% ../nbs/01_types.ipynb #56125ba3
from fastcore.basics import store_attr, basic_repr


# %% ../nbs/01_types.ipynb #bcd6a16c
class Symbol:
    "symbol is a `name` in Lisp"
    def __init__(self, s): store_attr()
    def __str__(self): return f"{self.s}"

    def __eq__(self, other): return isinstance(other, Symbol) and self.s == other.s
    def __hash__(self): return hash(self.s)
    
    __repr__ = basic_repr()

# %% ../nbs/01_types.ipynb #2a368749
class Macro:
    "holder of the function for late evaluation"
    def __init__(self, fn): store_attr()

# %% ../nbs/01_types.ipynb #66d47471
class Thunk:
    "a unit of computation that can be executed"
    def __init__(self, expr, env): store_attr()
